#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d 1 2 3    


bspc config border_width         2
bspc config window_gap          5
bspc config focused_border_color "#f38ba8"
bspc config normal_border_color "#1e1e2e"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          30
#AUTOSTART
$HOME/.config/polybar/launch.sh
 
